services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      DB_USER: postgres 
      DB_PASS: 137952 
      DB_NAME: authify 
      DB_HOST: db
      DB_PORT: 5432 
      JWT_SECRET: sI@X9d^jDi%1903$!#0@75#43$%^04&0! 
      REDIS_URL: redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: 137952 
      POSTGRES_DB: authify
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres_data:
